
export const ADD_TO_APPLIED = 'ADD_TO_APPLIED';
export const REMOVE_FROM_APPLIED = 'REMOVE_FROM_APPLIED';
export const ADD_ALL_TO_APPLIED ='ADD_ALL_TO_APPLIED';
export const REMOVE_ALL_FROM_APPLIED = 'REMOVE_ALL_FROM_APPLIED';
export const ADD_TO_LIKED = 'ADD_TO_LIKED';
export const REMOVE_FROM_LIKED = 'REMOVE_FROM_LIKED';
export const REMOVE_ALL_FROM_LIKED = 'REMOVE_ALL_FROM_LIKED';
